azukiapp/azk

src/cli/ui.js

All azk help `commands` outputs are sorted by name:

[azk help alphabetically] Sorting help in outputWithLabel #223

---

src/cmds/version.js

`azk version` now shows the `azk` in lowercase:

[azk lowercase] Showing azk in lowercase at azk version command #222

---

CHANGELOG.md
docs/content/en/SUMMARY.md
docs/content/en/azkfilejs/dns_servers.md
docs/content/pt-BR/SUMMARY.md
docs/content/pt-BR/azkfilejs/dns_servers.md
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
src/system/index.js

Adding support to customize DNS servers to will be used in system.
```javascript
systems({
'web': {
image: "azukiapp/node",
command: "node index.js",
workdir: "/azk/#{manifest.dir}",
http: {
domains: [ "#{system.name}.#{azk.default_domain}" ],
},
dns_servers: ['208.67.222.222', '208.67.222.220']
},
});
```

[system_dns] Adding support to `dns_servers` in system, #214

---

src/cmds/shell.js

I complemented the #211 feature to show log messages when `azk` is building an image. This happens when `Azkfile.js` uses a `Dockerfile` as an image.
```shell
$ azk shell
azk: ⇲ building `azkbuild/a4746dc0a9-my_app:6651ddff6eb82c840ced7c1dddee15c6e1913dd4` image...
root@241746bb3d60:/azk/my-app#
```
Now, it shows log messages when downloading or building an image.

[azk shell logs] Showing logs when building an image

---

CHANGELOG.md
src/cmds/shell.js
src/docker/build.js
src/images/index.js

This closes this https://github.com/azukiapp/azk/issues/253;
You can test with verbose `-v` option enabled:
```
azk start -v --rebuild
```

Showing docker logs when verbose is enabled

---

spec/system/index_spec.js
spec/utils/net_spec.js
src/system/index.js
src/utils/net.js

Fixing support to dns_servers (PR #273 )
To test:
- Add custom `dns_servers` in Azkfile.js:
```js
systems({
'web': {
image: "azukiapp/node",
command: "node index.js",
workdir: "/azk/#{manifest.dir}",
http: {
domains: [ "#{system.name}.#{azk.default_domain}" ],
},
dns_servers: ['208.67.222.222', '208.67.222.220']
},
});
```
- Run `azk shell` and check `/etc/resolv.conf` file:
```sh
$ azk shell
nameserver 192.168.50.4
nameserver 208.67.222.222
nameserver 208.67.222.220
```

[system_dns] Fixing support to dns_servers

---

CHANGELOG.md
spec/generator/court_spec.js
spec/generator/rules/generation/node_gen_spec.js
spec/generator/rules/node_spec.js
src/generator/rules/node.js
src/generator/sugestion_chooser.js
src/generator/suggestions/node012.js
src/generator/suggestions/node08.js

This closes https://github.com/azukiapp/azk/issues/276;
We had the rule but not the suggestion.
- Including new suggestions for new docker node version: 0.12, 0.10 e 0.8
- Fixing tests that now expect stable version to be node 0.12

Including new node.js versions

---

CHANGELOG.md
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
src/system/index.js

This pull request closes #287 issue.
Before this fix `azk` was not parsing the port correctly. In an example like:
```js
ports: {
http: "8080:80/tcp"
}
```
`8080` should be a "public" port, but it was a "private" port and `80` is a public port.

Fixing parse a public port in Azkfile.js

---

CHANGELOG.md
src/system/run.js

wait: timeout and retry defaults

---

docs/content/en/command-line/vm.md
docs/content/pt-BR/command-line/vm.md
shared/locales/en-US.js

This closes #260.
There were only references to azk vm install in the documentation, and in the command line output.

[invalid vm action] Removing azk vm install command reference

---

CHANGELOG.md
shared/locales/en-US.js
spec/cli/download_part_spec.js
spec/cli/smart_progress_bar_spec.js
src/cli/download_part.js
src/cli/helpers.js
src/cli/smart_progress_bar.js
src/images/index.js

As we do not know exactly the size to be downloaded, I've created the classes below to control the progress bar. It is based on the number of layers that will be downloaded. Each block is updated according to the progress of each layer.
file: cli/download_part.js
Is a download block. Receives the status message docker remote and sends the tick to the progress bar.
file: cli/smart_progress_bar.js
Manages a progress bar without knowing total size previously
```
$ azk start python34
azk: ↑ starting `python34` system, 2 new instances...
azk: ✓ checking `azukiapp/python:3.4` image...
azk: ⇲ downloading `azukiapp/python:3.4` image...
azk: ⇲ comparing registry layers and local layers...
azk: ⇲ pulling 11/29 layers.
[============================================     ] 91% 10/11 
azk: ✓ completed …
```

pull progress bar

---

CHANGELOG.md
shared/locales/en-US.js
spec/images/index_spec.js
src/images/index.js
src/manifest/index.js

This pull request:
- closes #250 issue.
- closes #302 issue.
Test instructions:
- Download [azkfile-init-examples](https://github.com/azukiapp/azkfile-init-examples):
```sh
git clone https://github.com/azukiapp/azkfile-init-examples
```
- Create and go to subfolder in `dockerfile-example`:
```sh
mkdir -p azkfile-init-examples/dockerfile-example/teste
cd azkfile-init-examples/dockerfile-example/teste
```
- run azk start
```sh
azk start
```

[fix_dockerfile_build] Fixing Dockerfile not use relative to manifest dir. #250

---

CHANGELOG.md
spec/fixtures/etc/resolv.conf
spec/utils/net_spec.js
src/agent/configure.js
src/config.js
src/utils/index.js
src/utils/net.js

This pull request closes #312 and closes #319 issue.
This feature, besides correcting the start problem of the agent of `azk` when not connected to the internet, brings improvements in the way the nameservers of the containers are resolved. If you change your network, you no longer have to restart the agent, just restart the containers.

[offline_start_agent] Correcting dns_servers when you can not read `/etc/resolv.conf`

---

CHANGELOG.md
shared/locales/en-US.js
spec/docker/build_spec.js
spec/fixtures/build/DockerfileBuildError
src/docker/build.js

This pull request closes #303 issue.
Now the AZK captures the error of build the Dockerfile:
```sh
$ azk nvm grunt --grep="invalids Dockerfile's should raise error for a invalid step"'
```

[raise_dockerfile_build] Fixing does not show the error when the Dockerfile not build, issue #303

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
shared/locales/en-US.js
spec/agent/vm_spec.js
src/agent/client.js
src/agent/configure.js
src/agent/index.js
src/agent/migrations.js
src/agent/vm.js
src/config.js
src/index.js
src/manifest/meta.js
src/utils/errors.js
src/utils/pid.js

This pull request brings major changes to how the `azk` agent handles the virtual machine, resulting in many improvements mainly (but not exclusively) to `azk` users using mac.
- Closes #116, adding swap support through this change in the image of the virtual machine: https://github.com/azukiapp/debian2docker/commit/6e1c93392629dc412d5c6b26a1363623ac863f8d
- Closes #305, this problem had to do with a failure in VirtualBox DHCP Server. If it was unable to provide an ip, that caused the start of other services (including docker) to fail. This was solved by removing the use of the DHCP Server system and substituting the fixed IP configuration system through  `guestproperty`, as can be seen in:: https://github.com/azukiapp/debian2docker/commit/885303981fd9a382a488b84f40ec099d3751e20f 
- …

Several improvements related to virtual machine and the agent

---

CHANGELOG.md
shared/locales/en-US.js
spec/manifest/index_spec.js
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
spec/system/run_spec.js
src/agent/configure.js
src/system/index.js
src/system/run.js
src/utils/net.js

This pull request closes issue #309 issue.
When the Dockerfile exposes some port, can happen of AZK try to connect to port exposed by Dockerfile, rather than the user-defined port at Azkfile.js.
- [azukiapp/azktcl](https://registry.hub.docker.com/u/azukiapp/azktcl/dockerfile/)
```
FROM scratch
EXPOSE 53/udp
EXPOSE 80
```
```js
systems({
'example': {
image   : { docker: 'azukiapp/azktcl' },
command: "socat TCP4-LISTEN:$HTTP_PORT,fork TCP:$BALANCER_IP:$BALANCER_PORT",
wait: true,
scalable: false,
ports: {
http: "81:81/tcp",
53: disable,
}
},
});
```
```sh
$ AZK_BALANCER_PORT=81 azk agent start
```
```sh
$ curl 192.168.50.4:81
```
```sh
$ azk nvm grunt --grep='should run and wait for port'
```

[Balancer] Fixing conflict at some port to be expected by the wait, issue #309.

---

CHANGELOG.md
spec/cmds/info_spec.js
src/cmds/info.js

This pull request closes #323 issue.
Run the `azk info` on a project that has a Azkfile.js
```sh
$ azk info
```

[info_manifest_id] Adding `manifest_id` on return of the command `azk info`, #323

---

CHANGELOG.md
src/images/index.js

This pull request closes #349 issues.
The `Images` was not getting the flag `--pull`, so the force pull is not working.
- Remove image and start
```
$ adocker rmi [image]
$ azk start
```
- Force pull
```
$ azk start --pull
```
- Start without pull
```
$ azk start
```

[Docker] Fixing flag `--pull` to force pull of docker image not working`

---

Azkfile.js

This PR updates Azkfile.js to support manifest dir name set by Jenkins ("workspace" instead of "azk" -- usually used)

[building_and_packaging] Updating Azkfile.js to support manifest dir name set by Jenkins

---

src/agent/index.js
src/cli/tracked_cmds.js
src/cmds/agent.js

This fixes azk tracking that was not sending the docker info;
- no more `this._command_tracked` check. Was not sending important info on  agent start command complete
- refactoring 'started' postal event to 'agent:started'
```sh
azk agent start --no-daemon
azk agent start
```
**go check**
- check if "command" on https://keen.io/project/5526968d672e6c5a0d0ebec6 has docker.version and vm (if you are using VM)
This PR was made on top of https://github.com/azukiapp/azk/pull/373

Fixing tracking agent start command

---

CHANGELOG.md
src/docker/docker.js
src/utils/tracker.js

This PR closes #372 
When stopping `azk agent`, some promises (regard tracking) remained unresolved, preventing the agent to stop.
Fixing it and handling properly bluebird (used by insight-keen-io) and Q (used by azk) promises, the agent can now be properly shutdown.

[fixing_agent_stop] Fixing issue on azk agent stop due to unresolved promises

---

spec/system/balancer_spec.js
spec/system/scale_spec.js

Couple tests were failing at ci-box, causing the build to fail.
Failed builds due to tests timeout:
* http://azkci.ngrok.com/job/azk-build/57/console
* http://azkci.ngrok.com/job/azk-build/43/console
Increasing the timeout value is not the best solution, it's just a workaround enough for now.

[ci] Increasing timeout values for tests failing at ci-box

---

Makefile

This PR fixes an issue when running `make` for the very first time (without `azk` in the PATH).

[make] Fixing Makefile assumption: azk is not in the $PATH at the first time

---

CHANGELOG.md
docs/content/en/reference/azkfilejs/shell.md
docs/content/en/reference/cli/shell.md
docs/content/pt-BR/reference/azkfilejs/shell.md
docs/content/pt-BR/reference/cli/shell.md
shared/locales/en-US.js
src/cmds/shell.js

This PR closes #378 
The `--mount` option of `azk shell` command was using the pattern `docker_folder:local_folder`, differently from its docs and help.
In order to make it comply with Docker's pattern, we preserved docs and help and fixed its implementation.

[cli] Fixing `azk shell --mount` option to comply with docs and help

---

CHANGELOG.md
shared/locales/en-US.js
src/utils/tracker.js

This PR closes #390 
Instead of a say-nothing stack trace, when tracking an event fails, a specific message should be properly logged using the `info` level.
This allow the user to know when tracker times out but doesn't show error messages by default.

[tracking] Fixing timeout message when tracking an event

---

CHANGELOG.md
gulpfile.js
spec/spec_helper.js
spec/spec_helpers/dustman.js

If you need to make `gulp watch: test --grep 'message'` without the `Agent` is running, you can now turn off this requirement.
```sh
$ gulp watch:test --grep 'message' --no-required-agent
```

[Test] Adding flag `--no-required-agent` to disable required `Agent` before tests.

---

docs/content/links.md

This PR closes #425.
Fixing link in our docs to Docker's ("Create a docker group" section).

[docs] Fixing link to docker docs (Create docker group)

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/images/index.js

This closes #407;
[`docker-registry-downloader`](https://www.npmjs.com/package/docker-registry-downloader) wasn't returning some errors, such as `404 - image not available`. This occurs because [`requestretry`](https://www.npmjs.com/package/requestretry) didn't identify this as an error. To solve this, I've made a change in the business logic that handle the result and throw the error if exists. See https://github.com/azukiapp/docker-registry-downloader/commit/5a3875a960a9691567c187276c4a99070d0572be.
In `azk`, due to a security reason, I've defined that, if the error isn't defined, it returns an empty string.
Change:
https://github.com/azukiapp/azk/commit/2798497ab9860a3eb6d61ac5d928e04e4ade9760#diff-b8227a104a604c03fa9304e391565997R101
Try to access shell to an invalid image:
```shell
$ …
```

[fix_registry_downloader] Fixing registry download error updating `docker-registry-downloader` to version v0.1.36.

---

CHANGELOG.md
shared/locales/en-US.js
src/agent/configure.js
src/sync/index.js

This PR closes #433.
Instead of simply assigning the output result to the `version_output` variable, now we accumulates each output result to the resulting variable, avoiding multiple calls of the `output` method to vanish the desired value (that should be returned in the first method call).
Plus, the version check regexp is fixed (expecting points instead of any character as version number separator).

[fix_get_rsync_version] Fixing rsync output handler to get its version

---

CHANGELOG.md
Makefile
docs/content/en/reference/azkfilejs/image.md
docs/content/pt-BR/reference/azkfilejs/image.md
package.json
spec/docker/build_spec.js
spec/fixtures/build/.dockerignore
spec/fixtures/build/Dockerfile
spec/fixtures/build/copy-entrypoint.sh
spec/fixtures/build/file2_dir/file2_to_add
src/docker/build.js

This PR closes #419.
Besides the support to `ADD . /toFolder/` instruction, that fixes the issue, an additional improvent has been done to support the same behaviour as [docker build](http://docs.docker.com/reference/builder).
Now you can use a [.dockerignore](http://docs.docker.com/reference/builder/#the-dockerignore-file) to avoid that `azk` sends to Docker's build API useless files to the image generation process.

[docker] Feature/fixing docker build

---

CHANGELOG.md
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
src/generator/court.js
src/generator/suggestions/django_python27.js
src/generator/suggestions/django_python34.js
src/generator/suggestions/django_python_default.js
src/generator/suggestions/node010.js
src/generator/suggestions/node012.js
src/generator/suggestions/node08.js
src/generator/suggestions/node_default.js
src/generator/suggestions/rails.js
src/generator/suggestions/ruby19.js
src/generator/suggestions/ruby20.js
src/generator/suggestions/ruby21.js
src/generator/suggestions/ruby22.js
src/generator/suggestions/ruby_default.js

Since we have the [`sync` mount option](http://docs.azk.io/en/reference/azkfilejs/mounts.html), the suggestions should generate manifest files with this option by default in languages/frameworks which performance can be degraded if this options is not used, such as:
* Ruby;
* Rails;
* Django (Python).

[Suggestions] Adding `sync` mount option to suggestions

---

CHANGELOG.md
shared/templates/Azkfile.mustache.js
src/generator/suggestions/node_default.js

This closes #358. 
It adds support for `envs_comment` in the Azkfile.mustache template. It also adds an initial setup for having the environment variable PORT in Node.js applications, after running `azk init`.

[Init] Improving Suggestions for Node.js

---

shared/locales/en-US.js
spec/generator/rules/generation/node_gen_spec.js
src/cmds/scale.js
src/cmds/start.js
src/cmds/status.js
src/generator/suggestions/django_python_default.js
src/generator/suggestions/elixir.js
src/generator/suggestions/jruby17.js
src/generator/suggestions/node_default.js
src/generator/suggestions/php.js
src/generator/suggestions/php55.js
src/generator/suggestions/php56.js
src/generator/suggestions/php_laravel.js
src/generator/suggestions/python27.js
src/generator/suggestions/python34.js
src/generator/suggestions/rails.js
src/generator/suggestions/ruby_default.js
src/system/index.js

[Scale] Fixing scalable.default = 0 and optimizing start, restart, status commands.

---

src/cli/cli_tracker_controller.js

After cli changes keen-io is not receiving the 'sub-commands' like `azk agent start`:
This fixes that.

Fixing sending command action to Keen-io

---

src/agent/configure.js
src/config.js

This PR intents to fix how `azk` checks if it's in the latest version.
The original way was GETting https://api.github.com/repos/azukiapp/azk/tags, but with new tags, such as `rc` build tags, this is broken.
The new way checks the `package.json` file from the branch `stable`, which means the latest stable release available in fact.

[Agent] Fix azk version check

---

spec/utils/tracker_spec.js
src/config.js
src/utils/tracker.js

This PR closes #398
To avoid conflict between the instruction if azk should either or not to track actions and Insight's original system, the class `InsightKeenIo` was extended in azk and the get/set methods for `optOut` was overridden in order to use metadata (where azk stores this kind of data).

[tracker] Fixing insightkeenio

---

src/agent/configure.js

This closes #444
Now its is not necessary to catch `agent.configure` errors when agent is starting.
This way the process will correctly stop when some errors occours.
Because of https://github.com/azukiapp/azk/blob/07ee52476c/src%2Futils%2Fpromises.js#L4-L11 no more `Unhandled Rejection` will be showed to final users.
To hold 80 port and test we can use socat:
```sh
sudo apt-get install socat
sudo socat TCP4-LISTEN:80,fork EXEC:"echo `pwd`"
```
To hold 80 port with azk container we can `kill -9` the process while azk agent is up:
```sh
kill -9 $(pgrep azk);
```

azk agent start: Fix configure errors

---

bin/azk
src/agent/api/index.js
src/agent/server.js
src/cmds/agent.js
src/config.js

This PR adds the current `azk` bin folder to the PATH.
This is useful when you have more than one `azk` bin in your machine and want to be sure which one you are running.
Plus, the code hot swap present in `azk agent` API has been disabled by default and can be turned on by setting env var `AZK_AGENT_HOTSWAP=true`

[Kernel] Adds current `azk` bin folder to the PATH

---

CHANGELOG.md
src/agent/configure.js
src/system/index.js

The sync feature wasn't properly handling applications located in subfolders.
The reason of that was the folders to be excluded from sync process were being considered related from mounting point, not from the destination folder to be synced.
Log before fix:
`Azkfile.js`:
In the previous example, the folders `tmp` and `log` should be excluded from sync once they are subfolders of a synced dir (`./#{system.name}`). However, because the mounting point was `.` (i.e. the folder where `Azkfile.js` is placed), the sync logic was looking for the non-existing folders `./tmp` and `./log` instead of `./#{system.name}/tmp` and `./#{system.name}/log`.

[Sync] Fixing sync excluded folders based on mount value instead of relative dir of sync

---

CHANGELOG.md
spec/generator/court_spec.js
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
src/generator/court.js
src/generator/suggestions/postgres-9.3.js
src/generator/suggestions/ruby.js

This PR includes two main changes:
- Inverts the order of analysis of systems evidences, processing the identification rules for frameworks before the ones for databases. This avoids that, in the suggested Azkfile.js, the database comes before the main app (as happened with Rails + PostgreSQL apps);
- From PR https://github.com/azukiapp/docker-postgres/pull/2, we've made a minor change to fix the volumes mounting for PostgreSQL.

[suggestion] Fixing suggestions: database order and postgresql mounts

---

CHANGELOG.md
shared/locales/en-US.js
src/agent/balancer.js
src/agent/server.js
src/config.js
src/utils/net.js

This change replaces the Virtual Machine periodic verification strategy by Docker service check, for both Mac OS X and Linux.
This should reduce issues with agent being stopped even when Docker is available.

[Agent] Replacing periodic check agent from vm to docker

---

shared/locales/en-US.js
src/agent/server.js
src/utils/net.js

- fixed agent to loop and use 50% of CPU
- showing log when agent check for docker:
- when starting agent, shows timeout now, not attempts count:

[Agent] fix agent loop

---

CHANGELOG.md
spec/manifest/validate/wait_spec.js
src/manifest/validate.js

In some cases you must set the `wait` as `false`, but the validation of the Manifest did not allow it. This PR adds a rule to allow the value `false`.
e.g. of error:
```shell
$ azk shell test
azk: Manifest file (`Azkfile.js`) is not valid (see  more at http://docs.azk.io/en/azkfilejs/), error:
azk: Error parsing `wait` value. Invalid type. Value: `false`.
azk: Please, change `test` system to a valid `wait` type and value.
azk: Check http://docs.azk.io/en/reference/azkfilejs/wait.html for further information.
```

[manifest] Fixing wait not support `false` value

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

This PR closes #481, closes #502 .
In Virtual Box 5.0, there is a slight change in the ouput of the command `VBoxManage showvminfo azk-vm-dev.azk.io --machinereadable`:
```
VideoMode="720,400,0"@0,0
VideoMode="720,400,0"@0,0 1
```
Updating [gullitmiranda/node-vboxmanage](https://github.com/gullitmiranda/node-vboxmanage), this isse was solved.

[kernel] Updating `vboxmanage` to fix parse in Virtual Box 5.0

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/agent/vm.js

A simple fix in VM removal: the issue is that `VM.remove` tried to remove DHCP servers even when no network interfaces existed in the VM

[vm] Fixing removal of VM without net interface

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/config.js
src/docker/docker.js
src/docker/index.js

To avoid possible incompatibility with newer versions of the docker, I added a setting that determines which version should be used.
You can change the version by environment variable `AZK_DOCKER_API_VERSION`.
For more information about the docker api versions visit https://docs.docker.com/reference/api/docker_remote_api/.

[docker] Adding docker api version lock

---

CHANGELOG.md
spec/docker/pull_spec.js
spec/docker/run_spec.js
spec/spec_helpers/dustman.js
src/config.js
src/docker/pull.js
src/system/run.js

Do not try to stop or kill a not running container
Break because of this change:
- 'docker kill returns error when container is not running' (https://github.com/docker/docker/blob/master/CHANGELOG.md)
to test this issue you can use this commit that have an error on command:
```
git clone https://github.com/saitodisse/task-cerebral.git
cd task-cerebral
git checkout 3bb9be151d2d9449a6595910ac858032efbd7bc9
azk start -Rvv
```
you should get this error if everything is correct:
```
azk: Run system `task-cerebral` return: (1), for command: /bin/bash -c npm run deploy && npm start:
azk:  .task-cerebral [log] >  
azk:  .task-cerebral [log] >  > task-cerebral@0.0.1 predeploy /azk/t4
azk:  .task-cerebral [log] >  > rm -rf dist/** && cp src/index.html dist && cp src/styles.css dist
```

[docker 1.8 fix] Fixing stopping/kill containers

---

docs/Azkfile.js
docs/content/en/troubleshooting/README.md
docs/content/pt-BR/troubleshooting/README.md

This PR is intended to improve `Troubleshooting` section in azk documentation:

[docs] Improving Troubleshooting section

---

CHANGELOG.md
spec/fixtures/build/.dockerignore
src/docker/build.js

This PR closes #520 .
Before using  `.dockerfile` content, azk now parses this content and remove empty lines and comments (lines started by `#`).
Also, the `.dockerignore` fixture was improved to cover those cases.

[Docker] Fixing how azk handles `.dockerignore` file on Dockerfile build

---

CHANGELOG.md
shared/templates/Azkfile.mustache.js
spec/generator/index_spec.js
spec/manifest/index_spec.js
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
src/system/index.js

This PR intends to improve support to env vars on http domains in the Manifest file.
The current behavior is to use the first domain in the `http.domains` array as the system hostname.
However, when using env vars as domains (useful for deployment, as instance), it may break.
The new behavior, removes empty values (in case those env vars are not set) and the use the first one. This way, it's possible to do the following:
*Azkfile.js*
```javascript
systems({
example: {
// ...
http: {
domains: [
"#{env.HOST_DOMAIN}",
"#{env.HOST_IP}",
"#{system.name}.#{azk.default_domain}",
]
}
}
});
```
```
$ HOST_DOMAIN= HOST_IP= azk status
┌───┬─────────┬───────────┬────────────────────┬─────────────────┬─────────────┐
│   │ System  │ Instances │ Hostname/url       │ Instances-Ports │ Provisioned │ …
```

[Manifest] Improving support to env vars on http domains

---

CHANGELOG.md
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
src/system/index.js

This PR adds `env` as a manifest system manifest templace, such as: `azk`, `manifest`, `system` etc.
With this template, one can refer to a env var inside the manifest file using:
```
#{env.FOO}
```
instead of
```
#{process.env.FOO}
```
It's cleaner and safer.

[Manifest] Adding `env` as a manifest system template

---

src/agent/server.js
src/config.js

This PR closes #525.
Add `AZK_DOCKER_MONITOR` env var which defaults to true if running on linux.

[Docker] If running inside vm, do not monitor Docker

---

src/generator/suggestions/mysql-5.6.js

Updating MySQL 5.6 suggestion: `MYSQL_PASSWORD` should be used instead of `MYSQL_PASS` ([reference](https://github.com/docker-library/mysql/blob/e892e8c52485535cce5dbadaba2c579fcc805f21/5.6/docker-entrypoint.sh#L68)).

[Suggestions] Updating MySQL 5.6 suggestion

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
shared/locales/usage-en-US.txt
spec/cmds/deploy_spec.js
spec/docker/pull_spec.js
spec/fixtures/slim-app/.env.sample
spec/fixtures/slim-app/Azkfile.js
spec/manifest/index_spec.js
spec/system/index_spec.js
spec/system/run_spec.js
src/cli/index.js
src/cmds/deploy.js
src/cmds/info.js
src/cmds/shell.js
src/cmds/start.js
src/docker/pull.js
src/manifest/get_project.js
src/system/index.js
src/system/run.js

But this change required some changes on how the container run command is get. Until now, `azk` used `/bin/sh -c` by default in order to run any command inside a container. However, in cases which the Docker image set a custom `CMD[...]`, this custom command was ignored and the behavior was different from the expected.
The consequences of this change is:
- For systems run on `azk start`, `/bin/sh -c` is not used (forced) anymore. Instead, the priority is: "property `command` defined in `Azkfile.js`" > "command defined by `CMD[...]` in the Docker image";
- For the command `azk shell`, the priority is: "option `--shell` passed to `azk shell`" > "property `shell` defined in `Azkfile.js`" > "command defined in `CMD [...]` in the Docker image" > "`/bin/sh`";
- The command `azk shell` offers …

[cli] Adding `azk deploy` command

---

CHANGELOG.md
src/generator/suggestions/php_laravel.js

Rodrigo Rigoni was facing problems with high CPU usage by `azk sync`. The problem of the reason was that the Azkfile.js suggested to Laravel applications did not have mounts for the folders `node_modules` and `vendor`, as they are in `.gitignore`.
Just add the following lines to the application of `mounts` that the problem should be solved.:
```js
mounts: {
// ...
'/azk/#{manifest.dir}/node_modules': persistent("./node_modules"),
'/azk/#{manifest.dir}/vendor'      : persistent("./vendor"),
},
```

[suggestions] Adding `node_modules` and `vendor` to laravel suggestion

---

docs/content/en/installation/README.md
docs/content/en/installation/linux.md
docs/content/en/installation/warning.md
docs/content/links.md
docs/content/pt-BR/installation/README.md
docs/content/pt-BR/installation/linux.md
docs/content/pt-BR/installation/warning.md
shared/scripts/install.sh

This PR improves the `install.sh` script:
- Checking Docker installation before adding Azuki apt repo in Ubuntu;
- Using 'dnf' package manager for Fedora 23;
- Replacing 'docker' with 'Docker';
- Adding 'stage' repo as an option;

[package] Improving installation script for Ubuntu and Fedora

---

CHANGELOG.md
docs/content/en/installation/express.md
docs/content/en/installation/linux.md
docs/content/pt-BR/installation/express.md
docs/content/pt-BR/installation/linux.md
shared/scripts/install.sh

When running `install.sh` (from http://www.azk.io/install.sh), it now will check for Docker. If it's not present, now it runs the script from https://get.docker.com/ in order to get it installed.

[Package] Improving install.sh: installing Docker before azk if it's not present

---

CHANGELOG.md
src/cli/cli_controller.js
src/cli/cli_tracker_controller.js
src/cli/helpers.js
src/cli/ui.js

The `UI` was not taking into consideration the `--quiet` sent as argument in the cli.
eg:
```shell
$ azk agent stop
$ azk status --quiet
azk: azk agent is required but is not running (try `azk agent status`)
```

[Cli] Fixing `ui.isInteractive()` not using option `--quiet`

---

CHANGELOG.md
docs/content/en/installation/express.md
docs/content/pt-BR/installation/express.md
shared/scripts/install.sh

This PR closes #578.
This changes allow installing azk using another shell besides `bash`:
```
curl -sSL http://azk.io/install.sh | sh
```
**Tested shells:**

[Package] Removing bashisms from azk installation script

---

spec/cmds/info_spec.js
src/agent/index.js
src/cli/cli_controller.js
src/cli/error_handler.js
src/config.js

Those errors weren't sent due to the agent startup process, that was designed to catch any error and make `azk` gracefully stop. So that, those errors didn't reach `src/cli/index.js` and, consequently, the error handler.

[Crash] Adding errors on agent startup and completion to the bug report.

---

Makefile
package.json
shared/scripts/ci-tests.sh

This PR intends to fix the chain of the test suite calls:
*Before:*
`npm` -> `make` -> `gulp`
*After:*
`make` -> `npm` -> `gulp`
Since running `make` is a requirement for `azk nvm npm` to be available, `make` should be called first.
Also, in `ci-tests.sh`, the used test command is `make test` to run the whole test suite.

[Cli] Fixing test suite calls

---

docs/content/en/installation/README.md
docs/content/en/installation/express.md
docs/content/en/installation/linux.md
docs/content/en/installation/upgrading.md
docs/content/pt-BR/installation/README.md
docs/content/pt-BR/installation/express.md
docs/content/pt-BR/installation/linux.md
docs/content/pt-BR/installation/upgrading.md
shared/scripts/install.sh

Now, the `install.sh` script can also update `azk` to its latest version.
It's just follow the instructions from [here](http://docs.azk.io/en/installation/#azk-express-installation).

[Package] Updating azk on `install.sh` script

---

spec/spec_helpers/dustman.js

This PR reverts the changes made by [this commit] (https://github.com/azukiapp/azk/blob/5c2eeb003ad02f8f1bf3df89c6af3e3855bd3b9d/spec/spec_helpers/dustman.js#L69-L74) in the file `spec/spec_helpers/dustman.js`.
This was causing the following error when the test suite was run without a running agent:
```
Before all tasks:
1) "before all" hook
events.js:72
throw er; // Unhandled 'error' event
^
TypeError: Cannot call method 'unsubscribe' of undefined
at azk-0.17.0 - spec/spec_helpers/dustman.js:71:23
at process._tickDomainCallback (node.js:492:13)
```

[Spec] Fixing error when tests were run without a running agent

---

CHANGELOG.md
src/system/run.js

This PR closes #615.
Instead of fixing permissions for `sync_folders` root folder (causing every file inside to be touched) every time a system was started, now only that system specific sync folder's permissions are fixed.

[Sync] Avoiding touching unrelated files when starting a system

---

.gitignore
CHANGELOG.md
Makefile
bin/azk
shared/scripts/install.sh
spec/cmds/version_spec.js
spec/index_spec.js
spec/manifest/get_project_spec.js
spec/utils/git_helper_spec.js
spec/utils/spawn_helper_spec.js
src/cmds/version.js
src/config.js
src/index.js
src/libexec/package-tools/arch/generate.sh
src/libexec/package-tools/mac/generate.sh
src/libexec/package-tools/mac/test.sh
src/libexec/package-tools/pack.sh
src/libexec/package-tools/test.sh
src/libexec/package-tools/ubuntu/generate.sh
src/manifest/get_project.js
src/utils/git_helper.js
src/utils/spawn_helper.js

this closes #605 
When we display `azk version` we do not have what exactly `git commit version`. This works well for released versions but for development `azk` version we need to know exactly what commit that we are running.
For this we will take the current commit being executed by git.
We also will include tests on `spawn_helper` and perhaps further improve the output of `azk version`
```sh
azk gulp test --grep 'Azk cli, version'
azk gulp test --grep 'should _gitspawn_VersionAsync get real current git version'
azk gulp test --grep 'Spawn Helper'
azk gulp test --grep 'Git Helper'
azk gulp test --grep 'git version:'
rm -rf /tmp/azkdemo; azk start azukiapp/azkdemo /tmp/azkdemo --git-ref benchmark -vv; (cd /tmp/azkdemo; azk stop)
```

[Cli] Include git commit on azk version

---

spec/utils/versions_spec.js
src/utils/index.js
src/utils/versions.js

the module `Versions` is an abstraction above the [semver](https://www.npmjs.com/package/semver).
```javascript
import { Versions } from 'azk/utils';
Versions.parse('~> 1.0'        ); // => '1.0.0'
Versions.parse('1.0 1.2'       ); // => '1.0.0'
Versions.parse('1.0.1 or 1.2.3'); // => '1.0.1'
// https://regex101.com/r/jQ6eE8/3
var regex = /elixir[\s]*\:[\s]*\"(?:[~> ]*)?([0-9.]+)(?:(?:[or ]*)?([0-9.]+))?(?:.*)?\".*/gm;
Versions.match(regex, 'elixir: "~> 1.2",'           ); // => ['1.0.0', '1.2.0']
Versions.match(regex, 'elixir: "~> 1.0.1 or 1.2.3",'); // => ['1.0.1', '1.2.3']
```
```
azk gulp test --grep "Azk Utils Versions"
```

Adding module `Versions` to `utils`

---

CHANGELOG.md
src/system/run.js

This PR intends to fix a bug in the `sync` mount.
When a symlink was intended to be synced, `sync` tried to run a `chown` over it. The bug occurs when the target file didn't exist in the `sync` container context.
Example:
```
mounts: {
'/azk/#{manifest.dir}' : sync("."),
'/azk/other/file'      : path("../file"),  // may or may not be mounted
}
```
```
$ ls -l ./link
lrwxrwxrwx 1 user users 27 Mar 31 19:28 link -> ../file
```
In this case, the `sync` occurs for the current dir (`.`), which contains a symlink named `link` that points to the file `../file`. In the `sync` container, the `file` doesn't exist, and the `chown` fails.
Adding the `-h` option, the `chown` command is applied to the symlink itself, instead of be applied to the target file.

[Sync] Fixing ownership of the symlink itself, not of the target file

---

Makefile
shared/scripts/install.sh
spec/cmds/init_spec.js
spec/integration/common/cmds/docker.bats
spec/integration/common/cmds/shell.bats
spec/integration/common/cmds/version.bats
src/cmds/init.js
src/libexec/package-tools/arch/generate.sh
src/libexec/package-tools/mac/generate.sh
src/libexec/package-tools/mac/test.sh
src/libexec/package-tools/pack.sh
src/libexec/package-tools/test-container.sh
src/libexec/package-tools/test.sh
src/libexec/package-tools/ubuntu/generate.sh

This PR intends to update azk scripts and tests for the changes from #614 
The command used to extract azk version from command line is:
```sh
$ azk version | sed -e 's/^azk //; s/^version //; s/,.*//'
```
This works for both old and new `azk version` output:
```sh
$ echo "azk version 0.17.0, build 2f55d48, date 2016-04-01" | \
sed -e 's/^azk //; s/^version //; s/,.*//'
#=> 0.17.0
$ echo "azk 0.17.0" | \
sed -e 's/^azk //; s/^version //; s/,.*//'
#=> 0.17.0
```

[Package] Updating how `azk version` is extracted from CLI

---

docs/content/en/installation/linux.md
docs/content/links.md
docs/content/pt-BR/installation/linux.md

Since [`azk` installation script](https://github.com/azukiapp/azk/blob/master/shared/scripts/install.sh) already supports Arch Linux (via `yaourt`), I'm adding instructions on docs for manual installation of azk on that SO.

[Docs] Adding Arch Linux as supported distribution

---

CHANGELOG.md
docs/content/en/reference/cli/info.md
docs/content/pt-BR/reference/cli/info.md
shared/locales/usage-en-US.txt
src/cmds/info.js

This PR adds the following options to the command `azk info`:
- `[<system>]`: just like in the commands `azk start` and `azk stop`, now it's possible to specify a system or a list of systems to retrieve info from;
- `--json`: the command output is formatted as a JSON;
- `--filter=[properties]`: a list of system properties to be shown (the default behavior is to show all of them);

[Cli] Adding more options to `azk info`

---

spec/cmds/doctor_spec.js
src/cli/ui.js
src/cli/views/version_view.js
src/cmds/version.js

This PR closes #508 
When the agent is down, `azk` falls back to retrieve Docker version from CLI using the command:
```
docker --version
```
Plus, the output has been slightly improved.

[Cli] Improving `azk version --full` output

---

src/libexec/package-tools/mac/test.sh
src/libexec/package-tools/pack.sh
src/libexec/package-tools/test-container.sh

Avoid running `azk` in `production` mode @ [CI](http://ci.azukiapp.com).
Plus, adding `--dry` option to run `pack.sh` in dry mode (just showing output, not runinng commands in fact).

[Package] Don't track events on packaging and testing

---

src/generator/suggestions/mysql-5.6.js

After `azk init` the mysql service does not started because this env is missing.

Adding mysql root password

---

CHANGELOG.md
docs/content/pt-BR/reference/azkfilejs/expandable_properties.md
spec/utils/shell_spec.js
src/system/index.js
src/utils/shell.js

- Closes #665;
- Fixes support special variables, like `${@}` and `${?}`;
- Adding image envs in expand options;
- Adding support escaped variables with `\`, like `echo \$PATH`;

[Core] Fixing many bugs in expand envs

---

src/cmds/version.js

This PR is a minor improvement for #653 , removing colored output from VM IP address.

[Cli] Removing colored output from 'azk version --full' command (VM IP address)

---

src/libexec/package-tools/mac/generate.sh

Since the `--HEAD` argument [was added](https://github.com/azukiapp/homebrew-azk/pull/8) into [`homebrew-azk`](https://github.com/azukiapp/homebrew-azk), it's needed to update the packaging scripts in order to generate a proper formula supporting this parameter.
This PR intends to do this fix.

[Package] Fixing Homebrew formula generated by 'pack.sh'

---

CHANGELOG.md
src/cli/index.js
src/cmds/scale.js

This PR intends to fix an issue occurring after the execution of `azk scale` command (see output below).
```
➜  azkdemo git:(master) ✗ azk scale azkdemo 2
┌───┬─────────┬───────────┬───────────────────────────┬────────────────────────────┬────────────────┐
│   │ System  │ Instances │ Hostname/url              │ Instances-Ports            │ Provisioned    │
├───┼─────────┼───────────┼───────────────────────────┼────────────────────────────┼────────────────┤
│ ↑ │ azkdemo │ 2         │ http://azkdemo.dev.azk.io │ 2-http:32769, 1-http:32768 │ 32 minutes ago │
│   │         │           │                           │                            │                │
└───┴─────────┴───────────┴───────────────────────────┴────────────────────────────┴────────────────┘
azk: Unknown error: "undefined" …
```

[Cli] Fixing error thrown on 'azk scale' command

---

CHANGELOG.md
src/agent/balancer.js
src/config.js

We now enable tweaking of various hipache config options via following
environment varables:
AZK_BALANCER_WORKERS
AZK_BALANCER_WORKER_MAX_SOCKETS
AZK_BALANCER_TCP_TIMEOUT
AZK_BALANCER_DEAD_BACKEND_TTL
Also increase tcpTimeout to 63 (from 30). 63 is a weird enough number
that it should tip of anyone who needs a bigger timeout to search for it
and thus easily discover how to increase.
To test this, start the agent with any/all of the above options and corresponding hipache settings should be visible in `~/.azk/data/run/hipache.json`. Some, like `workers` can also be seen to take effect by just looking at number of hipache processes running.

Make various hipache parameters user configurable
