azukiapp/azk

README.md

[![wercker status](https://app.wercker.com/status/c771315d3c499dec99c49f49e8d1d84a/s/master "wercker status")](https://app.wercker.com/project/bykey/c771315d3c499dec99c49f49e8d1d84a)

[wercker_badge] Changing Wercker badge to check only master branch

---

docs/content/en/SUMMARY.md
docs/content/en/contributing/README.md
docs/content/pt-BR/SUMMARY.md
docs/content/pt-BR/contributing/README.md

Adding a lot of info in pt-BR.
Explain how to contribute with `azk`:
- How to open issues
- Get support
- Run tests
- Code style
- Commit formats
- etc

[docs] Adding contributions

---

CHANGELOG.md
shared/locales/en-US.js
src/system/run.js

Now shows when a timeout occurs:

timeout error #217

---

.jscsrc
CHANGELOG.md
spec/generator/court_spec.js
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
spec/generator/rules/generation/mysql_gen_spec.js
spec/generator/rules/generation/node_gen_spec.js
spec/generator/rules/rails41_spec.js
spec/generator/rules/ruby_spec.js
src/generator/rules/rails.js
src/generator/rules/ruby.js
src/generator/suggestions/django_python27.js
src/generator/suggestions/django_python34.js
src/generator/suggestions/jruby17.js
src/generator/suggestions/mysql56.js
src/generator/suggestions/node010.js
src/generator/suggestions/php_laravel.js
src/generator/suggestions/postgres93.js
src/generator/suggestions/python27.js
src/generator/suggestions/python34.js
src/generator/suggestions/rails.js
src/generator/suggestions/ruby19.js
src/generator/suggestions/ruby20.js
src/generator/suggestions/ruby21.js
src/generator/suggestions/ruby22.js
src/utils/index.js

* Make and use [`azukiapp/mysql`](https://registry.hub.docker.com/u/azukiapp/mysql/) docker image.
* Adding `ruby 2.0` and `ruby 2.2` versions to [ `azukiapp/ruby`](https://registry.hub.docker.com/u/azukiapp/ruby/) docker image.
* Changing `rails` suggestions to use [ `azukiapp/ruby`](https://registry.hub.docker.com/u/azukiapp/ruby/) docker image.
* Fix issues #224 and #218.

[update_suggestions] Update suggestions images, rails, ruby, mysql. #224 #218

---

docs/content/en/azkfilejs/mounts.md
docs/content/en/getting-started/persisting-data.md
docs/content/pt-BR/azkfilejs/mounts.md
docs/content/pt-BR/getting-started/persisting-data.md

There was an error when going through the Getting Started application in docs, related to issue #313. Also more information on the mounts options, in the Azkfile.js section.

[docs] Updating getting started and adding more information on mounts option

---

docs/Azkfile.js
docs/content/en/SUMMARY.md
docs/content/en/agent/README.md
docs/content/en/faq/README.md
docs/content/en/getting-started/database.md
docs/content/en/getting-started/running-application.md
docs/content/en/troubleshooting/README.md
docs/content/pt-BR/SUMMARY.md
docs/content/pt-BR/faq/README.md
docs/content/pt-BR/getting-started/database.md
docs/content/pt-BR/getting-started/running-application.md
docs/content/pt-BR/getting-started/starting-agent.md
docs/content/pt-BR/troubleshooting/README.md

Adding two new sections to the docs, FAQ and Troubleshooting.
Also made some small changes to the getting started guide, and translated the information describing the agent that was already available in PT.

[docs] Adding faq and troubleshooting sections

---

docs/content/en/faq/README.md
docs/content/en/troubleshooting/README.md
docs/content/pt-BR/faq/README.md
docs/content/pt-BR/troubleshooting/README.md
spec/agent/vm_spec.js
src/agent/configure.js
src/agent/vm.js
src/cmds/doctor.js
src/utils/net.js

This PR:
* Closes #332;
* It's a complement to #331 and closes #309;
* Solves the slow connection via SSH to VM when offline on Mac OS X (via https://github.com/azukiapp/debian2docker/commit/87ac9cbc905893d1a38b85e9f9316225a1141d45);
* Improvements on docs;

[slow_ssh] Fixing slow ssh + refactoring DNS port logic when using VM

---

CHANGELOG.md
shared/locales/en-US.js
spec/docker/build_spec.js
spec/fixtures/build/Dockerfile
spec/fixtures/build/copy-entrypoint.sh
src/docker/build.js

This pull request closes #341 and closes #342 issues.

[Dockerfile] Fixing `azk build` does not support `COPY` in Dockerfile

---

src/system/run.js

This pull request closes #267 issue.
More info in #267.
**eg:**

[system_log_error] Distinguish azk error from sub-system log error

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
shared/locales/en-US.js
src/agent/configure.js
src/images/index.js
src/utils/errors.js
src/utils/net.js

This pull request closes #299 issue;
To test this pull request, simply disconnect the internet before or during the pull of the images.
**No internet connection**
**Lost internet connection**

[connection_error_msg] Check and show error message in the pull of docker images

---

docs/content/en/installation/linux.md
docs/content/pt-BR/installation/linux.md
shared/scripts/install.sh

This PR includes:
* `install.sh` now disables `dnsmasq`;
* improving `install.sh` log messages;
* updating docs (replacing `init.d`scripts with a `service` command to disable `dnsmasq`);

[updating_install.sh] Adding instructions to install.sh disable dnsmasq

---

src/libexec/package-tools/build.sh
src/libexec/package-tools/fedora/generate.sh
src/libexec/package-tools/fedora/install.sh
src/libexec/package-tools/fedora/test.sh
src/libexec/package-tools/mac/generate.sh
src/libexec/package-tools/mac/test.sh
src/libexec/package-tools/ubuntu/generate.sh
src/libexec/package-tools/ubuntu/install.sh
src/libexec/package-tools/ubuntu/test.sh

This PR adds several scripts to generate and test deb, rpm and brew packages.

[package-tools] Adding scripts to generate deb, rpm and brew packages

---

docs/content/en/SUMMARY.md
docs/content/en/installation/README.md
docs/content/en/installation/source-code.md
docs/content/pt-BR/SUMMARY.md
docs/content/pt-BR/installation/README.md
docs/content/pt-BR/installation/source-code.md

Adding a new sub section to the "Installation" section on installing from the source code

[docs] Adding instructions to install from source

---

.gitignore

Simply adding .env to .gitignore to avoid committing it into git.

[gitignore] Adding .env to .gitignore

---

docs/content/en/installation/source-code.md
docs/content/pt-BR/installation/source-code.md

Adding information about installing the libnss-resolver to installation from source section.

[docs] Updating installation from source instructions

---

docs/content/en/troubleshooting/README.md
docs/content/pt-BR/troubleshooting/README.md

Adding troubleshooting item about getting more performance turning off the assets debug mode.
This is about issue #379

[docs] getting more performance turning off the assets debug mode

---

docs/content/en/troubleshooting/README.md
docs/content/pt-BR/troubleshooting/README.md

Added the reference to Ruby on Rails guide website, regarding the debug setting to improve application speed. #379 
Thanks @dynaum

[docs] Adding reference link to troubleshooting Rails debug

---

docs/content/en/reference/azkfilejs/mounts.md
docs/content/pt-BR/reference/azkfilejs/mounts.md

This PR adds more information regarding PR #404 , and also issue #411

[docs] Improving Azkfile.js mounts reference section

---

docs/content/en/SUMMARY.md
docs/content/en/reference/azkfilejs/system_name.md
docs/content/pt-BR/SUMMARY.md
docs/content/pt-BR/reference/azkfilejs/system_name.md
src/manifest/index.js

This adds more information regarding PR #403

[docs] Adding Azkfile.js system name reference section

---

docs/content/en/getting-started/database.md

Just correct the language to EN.

Using correct language on getting started

---

docs/content/en/reference/azkfilejs/mounts.md
docs/content/en/troubleshooting/README.md
docs/content/pt-BR/reference/azkfilejs/mounts.md
docs/content/pt-BR/troubleshooting/README.md

This closes #411.
Small fix to mounts persistent documentation regarding the comments made on issue #411.

[docs] Clarifying information about mounts persistent on Mac

---

CHANGELOG.md
spec/fixtures/elixir_app/mix.exs
spec/fixtures/elixir_app/mix_phoenix.exs
spec/generator/rules/elixir_phoenix_spec.js
spec/generator/rules/elixir_spec.js
src/generator/index.js
src/generator/rules.js
src/generator/rules/elixir.js
src/generator/rules/elixir_phoenix.js
src/generator/suggestions/elixir.js
src/generator/suggestions/elixir_phoenix.js
src/generator/suggestions/index.js

This pull request closes #153 issue.
- Make class Suggestion to use with base;
- Removing (trim) multiple new_line before generate a new Manifestfile;
- Move method `getEvidence` to BaseRule;
- Adding `elixir_phoenix` suggestions;
- Adding `elixir` suggestions;

[Suggestions] improvements

---

spec/agent/vm_spec.js
spec/generator/rules/generation/mysql_gen_spec.js
src/cmds/scale.js
src/cmds/start.js
src/config.js
src/images/index.js
src/system/run.js

[Scale] Fixing exit code and error message in scale

---

src/libexec/package-tools/build.sh
src/libexec/package-tools/mac/generate.sh
src/libexec/package-tools/mac/test.sh

Adding `--publish` option (publishes to `repo-stage`) and `--no-tag` to not create git tag after all (default behavior does).

[package-tools] Improving post packaging process

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

This update in insight-keen-io lib improves how tracker starts a background process and sends data to tracker. In this way tracker becomes faster and doesn't block azk CLI.
Thanks @slobo for reporting the issue ;)

[tracking] Updating insight-keen-io

---

docs/content/en/troubleshooting/README.md
docs/content/pt-BR/troubleshooting/README.md

Updating docs Troubleshooting with two new sections:
1. The azk start command is not working
1. How can I clean Docker files?
1. How can I clean azk persistent files?
This PR closes #397
This PR closes #427

[Docs] Troubleshooting: azk start and clean

---

CHANGELOG.md
docs/content/en/reference/azkfilejs/wait.md
docs/content/pt-BR/reference/azkfilejs/wait.md
npm-shrinkwrap.json
package.json
shared/locales/en-US.js
shared/templates/Azkfile.mustache.js
spec/generator/court_spec.js
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
spec/manifest/validate/wait_spec.js
spec/manifest/validate_spec.js
spec/utils/net_spec.js
src/agent/balancer.js
src/agent/server.js
src/cli/helpers.js
src/config.js
src/generator/rules.js
src/generator/suggestions/index.js
src/generator/suggestions/mysql-5.6.js
src/manifest/validate.js
src/system/index.js
src/system/run.js
src/utils/net.js

```js
.timeout(opts.timeout)
.catch(function () {
return promiseResolve(false);
});
```
```js
wait: 20,
// will be deprecated
wait: { retry: 10, timeout: 1000 },
wait: { retry: 1, timeout: 0 },
```
```js
// not accepting negative values
wait: { retry: -1, timeout: 1000 },
wait: { retry: 1, timeout: -20 },
wait: -20,
// does not accept strings here, only numbers
wait: { retry: "1", timeout: 1000 },
wait: { retry: 1, timeout: "20" },
wait: "20",
```
This closes #148

[Manifest] short wait

---

shared/locales/en-US.js
spec/utils/net_spec.js
src/agent/server.js

This PR improves Docker monitor messages and fixes lint and a broken test

[Docker] Fixing Docker monitor

---

docs/content/en/agent/README.md

Change english agent docs to translate some words that were in portuguese

Documentation translation fixes

---

README.md
docs/content/en/installation/README.md
docs/content/en/installation/linux.md
docs/content/en/installation/warning.md
docs/content/links.md
docs/content/pt-BR/installation/README.md
docs/content/pt-BR/installation/linux.md
docs/content/pt-BR/installation/warning.md
shared/scripts/install.sh
src/libexec/package.sh

- docker.io -> docker-engine
unified docker installation: 
```sh
$ curl -sSL https://get.docker.com/ | sh
```

[docs] docker install changes

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
src/generator/court.js
src/generator/suggestions/elixir.js
src/generator/suggestions/elixir_phoenix.js
src/generator/suggestions/node.js
src/generator/suggestions/php_composer.js
src/generator/suggestions/postgres-9.3.js
src/generator/suggestions/ruby.js

In the process of application of the rendering of the suggestions there is an error with relative path, this error occurred when used relative path beyond `"."` the value of the mounts.
```javascript
// current:
mounts: {
'/azk/#{manifest.dir}/#{system.name}': sync("./#{system.name}"),
'/azk/bundler': persistent("./#{manifest.dir}/#{system.name}/bundler"),
'/azk/#{manifest.dir}/#{system.name}/tmp': persistent("./#{manifest.dir}/#{system.name}/tmp"),
'/azk/#{manifest.dir}/#{system.name}/log': path("./#{manifest.dir}/#{system.name}/log"),
'/azk/#{manifest.dir}/#{system.name}/.bundle': path("./#{manifest.dir}/#{system.name}/.bundle"),
},
// expected:
mounts: {
'/azk/#{manifest.dir}/#{system.name}': sync("./#{system.name}"),
'/azk/bundler': persistent("./#{system.name}/bundler"), …
```

[suggestions] Fixing relative mounts path in suggestions

---

CHANGELOG.md
src/config.js

* Enhancements
* [kernel] Separating development environment to be enabled with a single env
* [VM] Changing calculation of VM memory for 1/6 of host

[Kernel] Separating development environment to be enabled with a single env var

---

CHANGELOG.md
spec/integration/common/cmds/shell.bats
src/cmds/shell.js
src/system/run.js

Send the environment variable `TERM` to the interactive terminal in case it has not been set.

[cli] Sending `TERM` env if it's not set

---

Azkfile.js
CHANGELOG.md
Makefile
README.md
src/libexec/make
src/libexec/package-tools/fedora/generate.sh
src/libexec/package-tools/ubuntu/generate.sh
src/libexec/package.sh
src/sync/worker.js

- Refactoring `Azkfile` to simplify and use more azk properties;
- Adding a `make` script to force `make -e` in `package` system;
- Making `git` a suggested dependency;

Improving package scripts and systems 

---

docs/content/common/azkfilejs/node-mongodb.md
docs/content/common/azkfilejs/php-laravel.md
docs/content/common/azkfilejs/python-django.md
docs/content/common/azkfilejs/python-piramid.md
docs/content/en/SUMMARY.md
docs/content/en/starting-from-scratch/README.md
docs/content/en/starting-from-scratch/nodejs.md
docs/content/en/starting-from-scratch/php-laravel.md
docs/content/en/starting-from-scratch/php-wordpress-phpmyadmin.md
docs/content/en/starting-from-scratch/python-django.md
docs/content/en/starting-from-scratch/ruby-rails.md
docs/content/pt-BR/starting-from-scratch/README.md
docs/content/pt-BR/starting-from-scratch/nodejs.md
docs/content/pt-BR/starting-from-scratch/php-laravel.md
docs/content/pt-BR/starting-from-scratch/php-wordpress-phpmyadmin.md
docs/content/pt-BR/starting-from-scratch/python-django.md
docs/content/pt-BR/starting-from-scratch/ruby-rails.md

This PR enhaces `Start from scratch` section by:
* Fixes summary
* Adds Azkfile.js example to available languages

[Docs] Improvements in "Start from scratch"

---

docs/content/en/troubleshooting/README.md
docs/content/pt-BR/troubleshooting/README.md

[docs] Adding instructions to remove VM disk in troubleshooting

---

docs/content/common/azkfilejs/full_example.md
docs/content/common/azkfilejs/php_wordpress_mysql.md
docs/content/common/azkfilejs/ruby-rails.md

[docs] Updating examples

---

CHANGELOG.md
docs/content/en/reference/azkfilejs/provision.md
docs/content/pt-BR/reference/azkfilejs/provision.md
spec/spec_helpers/mock_manifest.js
spec/system/index_spec.js
spec/system/run_spec.js
src/cmds/info.js
src/system/index.js
src/system/run.js

This PR closes #571, closes #574.

[core] Fixing output error in provision step

---

CHANGELOG.md
docs/content/common/azkfilejs/php-cakephp.md
docs/content/en/SUMMARY.md
docs/content/en/starting-from-scratch/README.md
docs/content/en/starting-from-scratch/php-cakephp.md
docs/content/pt-BR/starting-from-scratch/README.md
docs/content/pt-BR/starting-from-scratch/php-cakephp.md
spec/generator/rules/php_cakephp_spec.js
src/generator/rules/php_cakephp.js
src/generator/suggestions/php_cakephp.js

Foi criado o Generator do Framework CakePHP com base no generator do Famework Laravel.

Create CakePHP generator and update documentation for the same

---

CHANGELOG.md
spec/generator/court_spec.js
spec/generator/rules/generation/mysql_and_postgres_gen_spec.js
src/generator/rules/postgres.js
src/generator/suggestions/php_laravel.js
src/generator/suggestions/postgres-9.4.js

Suggestions improvements

---

docs/README.md
docs/content/common/getting-started/persistent_example.md

Hi, there.
While going through the docs, I noticed that the `command` to start redis in persistent mode needs a little tweak.
How about this fix?
Cheers!

Array-like command for persistent redis

---

CHANGELOG.md
src/docker/build.js

[Core] fix build verbose

---

CHANGELOG.md
src/cmds/scale.js
src/docker/run.js
src/system/index.js
src/system/run.js

Verbose level 2 will show command output:
This closes #482

[Cli] azk start command verbose

---

npm-shrinkwrap.json
package.json
shared/locales/en-US.js
spec/cmds/config_spec.js
src/cli/error_handler.js
src/cli/views/ask_send_error_view.js

Using [validator](https://www.npmjs.com/package/validator) lib to validate user's email.
Plus, fixing a minor issue on `src/cli/views/ask_send_error_view.js` that was causing a lint error.

[Crash] Fixing email validation

---

spec/cli/error_handler_spec.js
spec/spec_helper.js
spec/sync/index_spec.js
src/agent/balancer.js
src/cli/error_handler.js
src/cli/helpers.js
src/cli/ui.js
src/cmds/info.js
src/cmds/init.js
src/cmds/logs.js
src/cmds/start.js
src/cmds/status.js
src/cmds/vm.js
src/docker/docker.js
src/images/index.js
src/sync/worker.js
src/utils/crash_report.js
src/utils/index.js
src/utils/net.js

I've added some examples of how to use `lazy_require` on azk.
I made some `Code Beautify` too

lazy_require docs

---

CHANGELOG.md
docs/content/common/azkfilejs/full_example.md
docs/content/common/azkfilejs/node-mongodb.md
docs/content/common/azkfilejs/python-django.md
docs/content/common/azkfilejs/python-piramid.md
docs/content/common/azkfilejs/ruby-rails.md
docs/content/common/getting-started/Azkfile_project_configure.md
docs/content/common/getting-started/mounts_example.md
docs/content/en/adding-services/ngrok.md
docs/content/en/getting-started/persisting-data.md
docs/content/en/reference/azkfilejs/command.md
docs/content/en/reference/azkfilejs/extends.md
docs/content/pt-BR/adding-services/ngrok.md
docs/content/pt-BR/getting-started/persisting-data.md
docs/content/pt-BR/reference/azkfilejs/command.md
docs/content/pt-BR/reference/azkfilejs/extends.md
spec/system/index_spec.js
src/system/index.js

Converting string commands to array when a Docker image has a defined `ENTRYPOINT`

[Core] Fixing command

---

CHANGELOG.md
Makefile
shared/scripts/install.sh
src/libexec/package-tools/arch/generate.sh

This PR intends to add support to Arch Linux to `azk`.
Related repositories:
- https://github.com/azukiapp/aur-libnss-resolver
- https://github.com/azukiapp/aur-libnss-resolver-git
- https://github.com/azukiapp/aur-azk
- https://github.com/azukiapp/aur-azk-git

[Package] Add support to Arch Linux

---

docs/content/en/installation/linux.md
docs/content/pt-BR/installation/linux.md

This PR closes #608
The supported Ubuntu versions are: 12.04, 14.04 and 15.10.

[Docs] Fixing supported Ubuntu versions

---

spec/utils/promises_spec.js
src/cmds/agent.js
src/cmds/vm.js
src/utils/errors.js
src/utils/promises.js

Fixing bug in `azk vm status`

---

docs/content/en/deploy/README.md
docs/content/pt-BR/deploy/README.md
shared/locales/en-US.js

This PR intends to give deployment instructions for users using the `Run Project` button.

Improving post run message after `azk start <git-repo>`

---

CHANGELOG.md
docs/content/en/terms-of-use/README.md
docs/content/pt-BR/terms-of-use/README.md

This PR intends to upgrade azk's TOS, required for `azk v0.17.0`.

[Docs] Upgrading azk's TOS

---

docs/content/common/azkfilejs/php_wordpress_mysql.md
docs/content/en/starting-from-scratch/php-wordpress-phpmyadmin.md
docs/content/pt-BR/starting-from-scratch/php-wordpress-phpmyadmin.md

Foi atualizado a DOC PT e EN de acordo com as atuais configurações necessárias para funcionamento do Wordpress.

update docs wordpress

---

spec/fixtures/elixir_app/mix_phoenix.exs
spec/generator/rules/elixir_phoenix_spec.js
spec/generator/rules/elixir_spec.js
spec/utils/versions_spec.js
src/generator/rules/elixir.js
src/generator/rules/elixir_phoenix.js
src/generator/suggestions/elixir-1.0.js
src/generator/suggestions/elixir-1.1.js
src/generator/suggestions/elixir-1.2.js
src/generator/suggestions/elixir_phoenix.js
src/utils/index.js
src/utils/versions.js

[generators] Adding suggestions to elixir v1.2

---

README.md

This PR fixes the contributing file link of the readme file.
It's a simple one.
Thanks.

[readme/fix-link] Fixing contributing file link of the readme file.

---

.github/ISSUE_TEMPLATE.md

1. What is this PR objective?
This PR intends to be more specific on the relation of VirtualBox and Mac OS X as we can observe on issue https://github.com/azukiapp/azk/issues/661.
Also adds a small Azkfile snippet to enforce user to paste it as a snippet, not a file.

[GH Templates] Improve GH issue template to be more specific on the relation of VirtualBox and Mac OS X

---

src/images/index.js

Ignore getDownloadInfo problems and try to proceed anyways

---

docs/content/en/reference/cli/restart.md
docs/content/en/reference/cli/scale.md
docs/content/en/reference/cli/shell.md
docs/content/pt-BR/reference/cli/restart.md
docs/content/pt-BR/reference/cli/scale.md
docs/content/pt-BR/reference/cli/shell.md

Update description for `restart`, `scale` and `shell` commands on docs for both en-US and pt-BR versions.

[Docs] Update description for restart, scale and shell commands
